#!/bin/bash
set +x

dev_env_home="$HOME/personal/dev"

log() {
    echo "[INFO] $1"
}

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            rm -rf $directory

            log "    copying env: cp $c $2"
	    cp -r ./$c $2
        done

    )
    popd &> /dev/null
}

copy() {
    log "removing: $2"
    rm $2
    log "copying: $1 to $2"
    cp $1 $2
}

update_files $dev_env_home/env/.config ~/.config
update_files $dev_env_home/env/.local $HOME/.local

copy $dev_env_home/env/.zsh_profile $HOME/.zsh_profile
copy $dev_env_home/env/.zshrc $HOME/.zshrc
