#!/bin/bash
set -x

sudo dnf -y in nodejs xclip npm ripgrep git wget curl python3-pip pavucontrol

sudo npm in --global yarn

# INSTALL GO
go_version="1.23.4"

if [ -d ~/.local/go ]; then
    sudo rm -rf ~/.local/go
fi
wget --output-document /tmp/go.linux-amd64.tar.gz https://go.dev/dl/go${go_version}.linux-amd64.tar.gz
sudo tar -xvf /tmp/go.linux-amd64.tar.gz -C /tmp
sudo mv /tmp/go ~/.local
sudo rm /tmp/go.linux-amd64.tar.gz
# END GO INSTALLATION

# INSTALL LUA
sudo dnf in -y lua luarocks
# END LUA INSTALLATION

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Flathub
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
