#!/bin/bash
set -xe

sudo pacman -S --noconfirm wget
sudo pacman -S --noconfirm python3-pip go
sudo pacman -S --noconfirm go

sudo pacman --noconfirm -S flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

sudo npm in --global yarn
