#!/bin/bash
set -x

version="1.23.4"

sudo rm -rf /usr/local/go
wget https://go.dev/dl/go${version}.linux-amd64.tar.gz
sudo tar -xvf go${version}.linux-amd64.tar.gz
sudo mv go /usr/local
sudo ln -s /usr/local/go/bin/* /usr/bin
sudo rm go${version}.linux-amd64.tar.gz
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

if [ -f "$HOME/.bashrc" ]; then
    echo -e "\n\nif [ -d \"\$HOME/go/bin\" ] ; then\n    PATH=\"\$HOME/go/bin:\$PATH\"\nfi" >> $HOME/.bashrc
fi
