#!/bin/bash
set -x

l_dir="$HOME/.local/lazygit"

if [ ! -d $l_dir ]; then
    git clone --depth 1 https://github.com/jesseduffield/lazygit.git $l_dir
fi

pushd $l_dir &> /dev/null
go install
popd &> /dev/null
