#!/bin/bash
set -x

version="0.11.2-1.fc42"

sudo dnf in -y neovim-$version

git clone --recursive https://github.com/gabriGutiz/termacro.nvim.git $HOME/personal/termacro

# Formatters
pip3 install black
pip3 install isort
pip3 install pycln

sudo dnf in -y clang-tools-extra

sudo npm install --global prettier

cargo install stylua --locked
