#!/bin/bash
set -x

version="v0.10.2"

if [ ! -d $HOME/neovim ]; then
    git clone --depth 1 https://github.com/neovim/neovim.git $HOME/neovim
fi

sudo apt -y install cmake gettext lua5.1 liblua5.1-0-dev

git -C ~/neovim fetch --all
git -C ~/neovim checkout $version

make -C ~/neovim clean
make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make -C ~/neovim install

git clone https://github.com/gabriGutiz/termacro.nvim.git $HOME/personal/termacro
