#!/bin/bash
set -x
set -e

version="0.11.2-1.fc42"

sudo dnf in -y neovim-$version

git clone --recursive https://github.com/gabriGutiz/termacro.nvim.git $HOME/personal/termacro

# Formatters
pipx install black
pipx install isort
pipx install pycln

sudo dnf in -y clang-tools-extra

sudo npm install --global prettier

cargo install stylua --locked
