#!/bin/bash
set -x

sudo apt update
sudo apt install -y git

if [ ! -d $HOME/personal ]; then
    mkdir $HOME/personal
fi

git clone --recursive https://github.com/gabriGutiz/env.git $HOME/personal/env

pushd $HOME/personal/env
./run
popd
