source = ~/.local/dev/config/hypr/start.conf
source = ~/.local/dev/config/hypr/bindings.conf
source = ~/.local/dev/config/hypr/looknfeel.conf
source = ~/.local/dev/config/hypr/input.conf
source = ~/.local/dev/config/hypr/windows.conf
source = ~/.local/dev/config/hypr/monitors.conf
