
######################################################################### OMARCHY
# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
#source = ~/.config/hypr/omarchy/default/hypr/autostart.conf
#source = ~/.config/hypr/omarchy/default/hypr/bindings/media.conf
#source = ~/.config/hypr/omarchy/default/hypr/bindings/clipboard.conf
#source = ~/.config/hypr/omarchy/default/hypr/bindings/tiling-v2.conf
#source = ~/.config/hypr/omarchy/default/hypr/bindings/utilities.conf
#source = ~/.config/hypr/omarchy/default/hypr/envs.conf
#source = ~/.config/hypr/omarchy/default/hypr/looknfeel.conf
#source = ~/.config/hypr/omarchy/default/hypr/input.conf
#source = ~/.config/hypr/omarchy/default/hypr/windows.conf
#source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
#########################################################################

source = ~/.config/hypr/omarchy/default/hypr/autostart.conf
source = ~/.config/hypr/omarchy/default/hypr/bindings/media.conf
source = ~/.config/hypr/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.config/hypr/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.config/hypr/omarchy/default/hypr/bindings/utilities.conf
source = ~/.config/hypr/omarchy/default/hypr/envs.conf
source = ~/.config/hypr/omarchy/default/hypr/looknfeel.conf
source = ~/.config/hypr/omarchy/default/hypr/input.conf
source = ~/.config/hypr/omarchy/default/hypr/windows.conf

## COPIED FROM :  https://wiki.hyprland.org/0.46.0/Configuring/Workspace-Rules/#smart-gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# Ignore maximize requests from apps. You'll probably like this.
# windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
